primus/eventemitter3

index.js
test.js

This introduces a new syntax, `removeListener(event, fn, context)` as public API. The previous API for removing once listeners as third argument was always undocumented and private. We should still bump a major version as this is still a breaking change.

[major] Allow listeners to be removed by context. #24

---

.travis.yml
README.md
index.js
package.json
test.js

This fixes this issue:
```js
var e = new EventEmitter()
, context = { foo: 'bar' };
function foo() {}
e.on('foo', foo, context);
e.removeListener('foo', foo, { baz: 'quux' });
e.listeners('foo').length === 1 // false, but the context is different
```

Fix contextual removal for events with only one listener

---

index.js

because now it fails with `Uncaught TypeError: Cannot convert a Symbol value to a string`.
[ES6 Symbols reference](http://www.2ality.com/2014/12/es6-symbols.html).

allow event name to be an ES6 Symbol

---

benchmarks/package.json
benchmarks/run/context.js
benchmarks/run/emit.js
benchmarks/run/hundreds.js
benchmarks/run/init.js
benchmarks/run/listeners.js
benchmarks/run/listening.js
benchmarks/run/multiple-emitters.js
benchmarks/run/once.js
benchmarks/run/remove-emit.js
benchmarks/template.js

I initially updated the benchmark tests to compare a new event emitter, **contra.emitter**.  
However, I also updated benchmarks to compare **eventemitter3@0.6.1** to latest **eventemitter3@master**.  The results may surprise you.
See my comment regarding the preliminary results on running `emit.js` - https://github.com/goatslacker/alt/pull/231

update tests, and add contra.emitter

---

index.js
test.js

This exposes a property called `prefixed` which stores the prefix or `false` when `Object.create()` is available.

Expose a `prefixed` property

---

index.js

This improves performance quite a bit by not having to do the same property lookup over and over. Also saves some bytes.

Make use of the available alias.

---

index.js
package.json
test.js

This adds a new method called `eventNames` that returns an array listing the events for which the emitter has registered listeners.
The same [method](https://github.com/nodejs/node/pull/5617/files) has been added in the EventEmitter that ships with node.
It will also helps us with https://github.com/unshiftio/ultron/issues/6.

Add `eventNames` method

---

index.js

This sligtly improves the `removeListener` performance when there is only one listener.
Result of `once.js` benchmark:
```
log:      Finished benchmarking: "EventEmitter3@1.2.0"
metric:   Count (51502), Cycles (5), Elapsed (5.592), Hz (913621.98)
log:      Finished benchmarking: "EventEmitter3(master)"
metric:   Count (55202), Cycles (4), Elapsed (5.583), Hz (978589.2)
info:     Benchmark: "EventEmitter3(master)" is the fastest.
```
Result of `listening.js` benchmark:
```
log:      Finished benchmarking: "EventEmitter3@1.2.0"
metric:   Count (58987), Cycles (5), Elapsed (5.745), Hz (1090032.06)
log:      Finished benchmarking: "EventEmitter3(master)"
metric:   Count (64261), Cycles (9), Elapsed (5.706), Hz (1181078.63)
info:     Benchmark: "EventEmitter3(master)" is the fastest.
```

Improve `removeListener` performance

---

index.js
test.js

With this patch the `_events` property will be set at instantiation time.
**Advantages**:
- Slightly improved perfomances (We don't have to check if `_events` is there every time)
- Smaller size
**Disadvantages:**
- Breaking change (see below)
- Slower initialization
**This is a breaking change because it affects inheritance. The child class must call the super constructor:**
```js
const EventEmitter = require('eventemitter3');
const util = require('util');
function Foo() {
EventEmitter.call(this);
}
util.inherits(Foo, EventEmitter);
```
The speed-up is not jaw dropping but still significant, here are the results of the benchmarks:
```
Starting benchmark context.js
log:      Finished benchmarking: "EventEmitter3@1.2.0"
metric:   Count (299191), Cycles (6), Elapsed (5.604), Hz (5613026.04) …
```

Set the _events property at instantiation time

---

index.js

fix removeAllListeners jsdoc

---

benchmarks/README.md
benchmarks/package.json
benchmarks/run/context.js
benchmarks/run/emit.js
benchmarks/run/hundreds.js
benchmarks/run/init.js
benchmarks/run/listeners.js
benchmarks/run/listening.js
benchmarks/run/multiple-emitters.js
benchmarks/run/once.js
benchmarks/run/remove-emit.js
benchmarks/template.js

- Make the benchmarks results easier to read by only showing ops/sec
- Remove the `devnull` dependency in favor of `console.log`
- Update [`benchmarks/README.md`](https://github.com/primus/eventemitter3/blob/e2c2248596161ba5005b7bdd93da58a0e9a4709b/benchmarks/README.md) with fresh data

Make benchmarks results easier to read

---

index.js
test.js

The `module.exports = someFunction` pattern is incompatible with ES6 imports. This change allows ES6-compatible environments (such as TypeScript or Babel) to import eventemitter3:
``` js
import { EventEmitter } from 'eventemitter3';
```

Expose eventemitter3 for ES6-style imports

---

index.d.ts
package.json

This pull request adds TypeScript bindings for the public interface of eventemitter3 (See issue #67).
The typings were written in the UMD style - that is, they will work correctly for scripts using module loaders as well as for scripts that reference `EventEmitter` as a global.

TypeScript Bindings

---

index.d.ts

As described in #104, I was having issues with the type definitions. I made these changes locally and it worked. My only concern is I don't have a great idea about backwards compatibility with older versions of the typescript compiler (I'm using 2.7.1 -- the latest stable).
see: https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-class-d-ts.html

fix module export for class

---

index.d.ts

This would allow users to verify that they only use events that they intend to.
e.g.
```
type AnyEvent = "ready" | "error" | "message";
class Foo extends EventEmitter<AnyEvent> { ... }
let instance = new Foo();
instance.on("ready", () => doSomething()); // Works fine
instance.on("bar", () => doSomething()); // Error
```

Allow user to specify supported events (TypeScript)

---

README.md

Just a small typo fix. Also, thanks for making this lib!

Typo fix `preperndOnceListener` -> `prependOnceListener`

---

index.d.ts

This is purely an extension to the current typings, and should be backwards compatible for code, but requires the TypeScript 3.0+ compiler. In addition to allowing you to specify event names (as with the current typings):
```typescript
const ee = new EventEmitter<'foo' | 'bar'>();
```
you can alternatively pass an interface that maps event names to a tuple of argument types:
```typescript
interface MyEvents {
foo: [string];
bar: [number, number];
}
const ee = new EventEmitter<MyEvents>();
ee.emit('foo', 'hello');
ee.emit('bar', 1, 2);
```
This provides strongly typed arguments for `on`, `off`, `emit`, etc.

Allow user to specify argument types for events

---

README.md

It was unclear that someone have to run `npm i` in the benchmarks folder. This small PR add a clarification in Readme.

Note on Readme for benchmarks install

---

index.d.ts

This PR fixes the type error reported in https://github.com/primus/eventemitter3/pull/219 and https://github.com/primus/eventemitter3/issues/222.

fix type error on named export

---

index.d.ts

Fixes #225. This PR makes the type definitions compatible with TypeScript 3.9.

Make type definitions compatible with Typescript 3.9

---

index.d.ts

This PR fixes the same issue that #231 was addressing. The PR didn't properly fix the issue.
The underlying problem was that TypeScript now requires an index signature for object types as currently used in the type constraint for `ValidEventMaps`.
The PR relaxes the type constraint to allow arbitrary object types. The event emitter will recognise all keys `K` of the object type `T` as event names.
The existing behaviour does not change: If the type `T[K]` is an array type, it is used as the type of the event args. If it is a function type, the parameter type of the function becomes the type of the event args.
The new behaviour is that for keys where `T[K]` is neither a function nor an array type, the argument type for the event `K` now becomes `any[]`.
This fixes the bug and the …

Reduce type constraints

---

index.d.ts

See also: #233 (i pulled the doc comment from here), #232, #231
The old types prevented
```ts
interface MyEventListeners {
print(message: string): void
}
class MyEmitter extends EventEmitter<MyEventListeners> {
emit<Event extends keyof MyEventListeners>(
event: keyof MyEventListeners
...args: Parameters<MyEventListeners[Event]>
) {
// customizations
return super.emit(event, ...args);
}
}
```
from working properly, as typescript borked where it fails to match
the arguments types with impossible-to-reach types.
The smallest change to achieve this fix is to change the `any[]` in `Arguments<...>` to `never`.
to understand this change, understand that the reference to the `Arguments` type will _never_ reach the `any[]` case from within the `EventListener` type mapping, since `K` already must …

fix: refine the types more, to improve type extends behaviour

---

package.json

I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 
Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.

[fix] move `types` condition to the front
